### ISSUE TITLE
ioNetty error when logging into MP Server

### ISSUE THREAD

**Issue by jaded33** [finallion/Artificial_Foliage-FABRIC-#7]
[17:10:38] [Netty Epoll Server IO #6/ERROR]: java.lang.IllegalArgumentException: Packet too big (is 2850954, should be less than 2097152): net.minecraft.class_2788@56d7c7f0

I have not been able to use any update of this mod.  The only version that works on my clients/server is version 1.0.  Each version since then gives me this Packet too big error and doesn't allow me to connect to server.

I have Better Minecraft fabric with many of my own custom additions to it that I run.
I run your mod on client and server, as I said the 1.0 version runs fine, but since 1.1-1.4 I have not been able to use it.

**Comment by finallion** [comment]
Could you post the full log please?

**Comment by jaded33** [comment]
Yes I will get you a full log next time I try the mod.  Redid the server the other day and old logs are gone.

**Comment by SplendidAlakey** [comment]
Hello, I have the same exact issue and since OP did not have a log, I can provide mine instead. 

> [06:38:32] [main/INFO]: Loading for game Minecraft 1.17
[06:38:33] [ForkJoinPool-1-worker-3/WARN]: The mod "libcd" contains invalid entries in its mod json: - Unsupported root entry "licence" at line 9 column 12
[06:38:33] [ForkJoinPool-1-worker-15/WARN]: The mod "libcd" contains invalid entries in its mod json: - Unsupported root entry "licence" at line 9 column 12
[06:38:33] [ForkJoinPool-1-worker-7/WARN]: The mod "libcd" contains invalid entries in its mod json: - Unsupported root entry "licence" at line 9 column 12
[06:38:33] [ForkJoinPool-1-worker-11/WARN]: The mod "cotton-config" contains invalid entries in its mod json: - Unsupported root entry "licence" at line 7 column 12
[06:38:33] [ForkJoinPool-1-worker-11/WARN]: The mod "cotton-logging" contains invalid entries in its mod json: - Unsupported root entry "licence" at line 7 column 12
[06:38:33] [main/WARN]: Warnings were found! - Conflicting versions found for fabric-api-base: used 0.3.0+a02b44633d, also found 0.3.0+a02b4463d5, 0.3.0+a02b4463a0 - Conflicting versions found for fabric-api-lookup-api-v1: used 1.2.0+84310a227d, also found 1.2.0+2b5c62d03d - Conflicting versions found for fabric-resource-loader-v0: used 0.4.7+b7ab6121a0, also found 0.4.7+b7ab6121d5, 0.4.7+b7ab61213d
[06:38:33] [main/INFO]: [FabricLoader] Loading 193 mods: cloth-common-events-v1@2.0.54, step-height-entity-attribute@1.0.0, trinkets@3.0.0, fabricloader@0.11.3, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1, morevillagers-fabric@2.0.1-SNAPSHOT, mcdar@1.3.0, fabric-dimensions-v1@2.0.10+a02b44633d, light-fix@1.0.0, java@16, megane@5.0.0, fabric-game-rule-api-v1@1.0.6+a02b44633d, helpwanted@1.1.0, fabric-api-base@0.3.0+a02b44633d, megane-vanilla@5.0.0+1.17, dynocaps@1.8.1, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.20, silkspawners@1.0.2, dawn@2.0.3, fabric-networking-v0@0.3.2+92519afa3d, scorch@1.0.0, flytre_lib@0.2.18, fabric-api-lookup-api-v1@1.2.0+84310a227d, lapisreserve@1.0.8, repurposed_structures@2.0.1+1.17.0, modmenu@2.0.0-beta.7, cloth-utils-v1@2.0.54, invisiblights@7.1+1.17, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.20, fabric-crash-report-info-v1@0.1.5+be9da3103d, megane-base@5.0.0, mcsa@2.3.2-1.17, fabric-key-binding-api-v1@1.0.4+a02b44633d, megane-runtime@5.0.0, bigbeacons@1.2.2, magna@0.3.0-1.17-pre4, libblockattributes_fluids@0.9.0, adorn@2.0.0+1.17, fabric-networking-api-v1@1.0.11+b7ab61213d, fallingtree@2.12.0, charm@3.2.2, toms_storage@1.1.12, veinmining@0.0.10-1.17, darkpaintings@3.0.6, terraform-shapes-api-v1@1.0.4, dazzle@1.0, linkedstorage@1.3.11-1.17, onsoulfire@1.17-1, fabric-structure-api-v1@1.1.11+e36969833d, fabric-object-builder-api-v1@1.10.9+b7ab61213d, megane-team-reborn-energy@5.0.0+0.1.1, vanillaplusbiomes@0.3.2, arfo@1.3, mcdw@3.2.2-1.17, fabric-rendering-data-attachment-v1@0.1.5+a02b44633d, mcda@1.6.4, speedyhopper@1.1-1.17-1, reach-entity-attributes@2.1.1, fabric-lifecycle-events-v1@1.4.4+a02b44633d, cardinal-components-util@3.0.0, fabric-loot-tables-v1@1.0.4+a02b44633d, libblockattributes_core@0.9.0, minecraft@1.17, fabric-command-api-v1@1.1.1+a02b44633d, jankson@3.0.1+j1.2.0, netherite_items@1.1.0, fasttransferlib@0.4.2, megane-fast-transfer-lib@5.0.0+0.4.2, fabric-renderer-indigo@0.4.8+a02b44633d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0, libninepatch@1.1.0, advancements-enlarger@0.2.4, somnus@0.0.12-1.17, libgui@4.0.0+1.17, cardinal-components@3.0.0, fabric-entity-events-v1@1.1.0+a02b44633d, xaerominimap@21.12.2, fabric-rendering-v0@1.1.2+92519afa3d, croptopia@1.5.0, fabric-rendering-v1@1.6.0+a02b44633d, omega-config@1.0.8, megane-industrial-revolution@5.0.0+1.10.0-alpha.4, fabric-tag-extensions-v0@1.1.4+a02b44633d, blue_endless_jankson@1.2.1, inmis@2.3.1-1.17, appleskin@mc1.17-2.0.0, lifts@1.1.2-BETA+1.17, cloth-api@2.0.54, cloth-datagen-api-v1@2.0.54, dragonloot@1.0.8, fabric-events-lifecycle-v0@0.2.1+92519afa3d, team_reborn_energy@0.1.1, customportals@2.0.2, tweed@3.0.0-beta.22, magic_mirror@1.3.0, fabric-keybindings-v0@0.2.2+36b77c3e3d, artifice@0.15.3+21w07a, indrev@1.10.0-alpha.7, architects_palette@1.2, villagernames@2.0.0, backslot@1.1.13, xaeroworldmap@1.14.4, fiber@0.23.0-2, twigs@1.0.1, consistency_plus@0.3.3-build.261_UNMINIFIED, cardinal-components-level@3.0.0, ppig@2.0, fabrilousupdater@2.2, com_moandjiezana_toml_toml4j@0.7.2, org_jetbrains_kotlin_kotlin-stdlib@1.5.20, fabric-blockrenderlayer-v1@1.1.5+a02b44633d, simple_backpack@1.1.11, libblockattributes_items@0.9.0, fabric@0.36.0+1.17, respawnablepets@1.17-1, cardinal-components-scoreboard@3.0.0, clayrecipefabric@2.0.0, cotton-config@1.0.0-rc.7, fabric-screen-handler-api-v1@1.1.8+a02b44633d, fabric-tool-attribute-api-v1@1.2.12+b7ab61213d, elementalcreepers@1.4.0, cloth-client-events-v0@2.0.54, enchant_giver@1.1.0, blockus@2.2.3+1.17, fabric-events-interaction-v0@0.4.9+a722d8c03d, wthit@3.6.1, fabric-language-kotlin@1.6.2+kotlin.1.5.20, patchouli@1.17-52-FABRIC-SNAPSHOT, artisanat@2.1, cloth-config2@5.0.34, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0, backslotaddon@1.0.4, fabric-resource-loader-v0@0.4.7+b7ab6121a0, malilib@0.10.0+dev.22, org_jetbrains_kotlin_kotlin-reflect@1.5.20, expandedstorage@7.0.0-alpha.31, cardinal-components-entity@3.0.0, architectury@2.0.16, fabric-commands-v0@0.2.2+92519afa3d, fabric-registry-sync-v0@0.7.10+e2961fee3d, cardinal-components-base@3.0.0, fabric-mining-levels-v0@0.1.3+92519afa3d, earthtojavamobs@1.7.1+1.17, fabric-item-groups-v0@0.2.10+b7ab61213d, fabric-models-v0@0.3.0+a02b44633d, megane-lib-block-attributes@5.0.0+0.9.0, witherite@0.0.5, bedrockify@1.1.1+mc1.17, truerooms@1.1.4, fabric-renderer-api-v1@0.4.3+676f40fa3d, wandering_collector@1.0.2+mc1.17, inventorysorter@1.7.9-1.17, libcd@3.0.3+1.16.3, cardinal-components-block@3.0.0, cavebiomes@0.6.3, flonters@1.2.0+1.17, fabric-containers-v0@0.1.12+a02b44633d, death_controls@1.1.0, clumps@fabric-1.17-7.0.0.2, dual_riders@1.0.5, comforts@0.0.4-1.17, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1, fabric-textures-v0@1.0.6+a02b44633d, cardinal-components-item@3.0.0, com_electronwill_night-config_core@3.6.2, fabric-rendering-fluids-v1@0.1.13+a02b44633d, cloth-scissors-api-v1@2.0.54, cotton-logging@1.0.0-rc.4, stitchedsnow@1.0.3, cardinal-components-chunk@3.0.0, fabric-renderer-registries-v1@3.2.0+a02b44633d, fabric-particles-v1@0.2.4+a02b44633d, forgottenrecipes@1.0.1, fabric-networking-blockentity-v0@0.2.11+a02b44633d, cloth-basic-math@0.5.1, amecsapi@1.1.5+mc21w16a, fabric-screen-api-v1@1.0.4+155f865c3d, com_electronwill_night-config_toml@3.6.2, fabric-item-api-v1@1.2.4+a02b44633d, roughlyenoughitems@6.0.260-alpha, pettable@1.2.0, kyrptconfig@1.1.10-1.17, stickyhopper@2.3-1.17-1, completeconfig@1.0.0, fabric-content-registries-v0@0.2.2+a02b44633d, cardinal-components-world@3.0.0, fabric-biome-api-v1@3.1.11+c345aea83d, advanced_runtime_resource_pack@0.2.9, lakeside@1.1.0+1.17, carrier@1.8.0, fabric-object-builders-v0@0.7.3+a02b44633d, fake-player-api@0.2.0, secretrooms@1.0.0+1.17
[06:38:33] [main/WARN]: Mod `appleskin` (mc1.17-2.0.0) does not respect SemVer - comparison support is limited.
[06:38:33] [main/WARN]: Mod `consistency_plus` (0.3.3-build.261_UNMINIFIED) does not respect SemVer - comparison support is limited.
[06:38:33] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/sid_2781967/minecraft_fabric/fabric.jar Service=Knot/Fabric Env=SERVER
[06:38:34] [main/WARN]: @Mixin target net/minecraft/class_3353$class_3354 is public in charm.mixins.json:accessor.MineshaftCorridorAccessor and should be specified in value
minecraft:empty 0
minecraft:bastion/starts 4
minecraft:bastion/units/center_pieces 3
minecraft:bastion/units/pathways 2
rate limit exceeded
minecraft:pillager_outpost/base_plates 1
[main/INFO][ResourceHandler] Loading Prefabs:
[main/INFO][ResourceHandler] Loading Templates:
[main/INFO][ResourceHandler] Loading Tweakers:
[06:38:44] [main/INFO]: Setting up a new Charm-based module 'charm'
[06:38:44] [main/INFO]: [STDOUT]: charm:dungeons/forest/starts 3
[06:38:44] [main/INFO]: [STDOUT]: charm:dungeons/mountains/starts 3
[06:38:44] [main/INFO]: [STDOUT]: charm:dungeons/plains/starts 4
[06:38:44] [main/INFO]: Initialising module Core
rate limit exceeded
[06:38:46] [main/INFO]: [STDOUT]: Speedy Hopper mod loaded!
[06:38:46] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$bfg000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[06:38:47] [main/INFO]: Trying to read config file...
[06:38:48] [main/INFO]: Industrial Revolution has initialized.
[06:38:48] [main/INFO]: [STDOUT]: index is:124
[06:38:51] [main/INFO]: Consistency+ Main - Finished initialization
[06:38:51] [main/INFO]: [Clay Recipe] Initializing 'Clay Recipe' under the ID 'clayrecipefabric'
[06:38:51] [main/INFO]: Mod Initialized!
rate limit exceeded
[06:38:53] [main/INFO]: Discovered plugin waila:vanilla at mcp.mobius.waila.plugin.vanilla.WailaVanilla
[06:38:53] [main/INFO]: Discovered plugin megane:plugin at badasintended.megane.runtime.Megane
[06:38:54] [main/INFO]: [Earth2Java] Mod loaded! Enjoy :D
[06:38:54] [main/INFO]: initializing Witherite
[06:38:55] [main/INFO]: Loading Xaero's Minimap - Stage 1/2 (Server)
[06:38:58] [main/INFO]: Applied 4668 biome modifications to 149 of 149 new biomes in 1.269 s
[06:38:58] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[06:38:59] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[06:38:59] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[06:38:59] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, xxxx]
rate limit exceeded
[06:39:00] [Worker-Main-9/ERROR]: Couldn't load tag c:flowers as it is missing following references: #c:tall_flowers (from Earth2Java)
[06:39:02] [Worker-Main-14/ERROR]: Parsing error loading recipe magic_mirror:magic_mirror_break com.google.gson.JsonSyntaxException: Unknown item 'magic_mirror:magic_mirror_treasure' at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?] at java.util.Optional.orElseThrow(Unknown Source) ~[?:?] at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?] at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[intermediary-server.jar:?] at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?] at net.minecraft.class_1867$class_1868.method_8144(class_1867.java:98) ~[intermediary-server.jar:?] at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:83) ~[intermediary-server.jar:?] at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:79) ~[intermediary-server.jar:?] at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?] at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?] at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?] at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?] at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?] at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?] at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:?] at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:?] at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:?] at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?] at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?] at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?] at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?] at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?] at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?] at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
[06:39:02] [Worker-Main-14/ERROR]: Parsing error loading recipe twigs:stripped_bamboo_planks com.google.gson.JsonSyntaxException: Unknown item tag 'twigs:stripped_bamboo_logs' at net.minecraft.class_1856.method_17873(class_1856.java:164) ~[intermediary-server.jar:?] at net.minecraft.class_5415.method_33166(class_5415.java:49) ~[intermediary-server.jar:?] at net.minecraft.class_1856.method_8107(class_1856.java:164) ~[intermediary-server.jar:?] at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?] at net.minecraft.class_1867$class_1868.method_8144(class_1867.java:98) ~[intermediary-server.jar:?] at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:83) ~[intermediary-server.jar:?] at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:79) ~[intermediary-server.jar:?] at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?] at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?] at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?] at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?] at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?] at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?] at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?] at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) [?:?] at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) [?:?] at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:?] at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?] at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?] at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?] at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?] at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?] at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?] at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
[06:39:02] [Worker-Main-14/INFO]: Loaded 20 recipes
[06:39:03] [Worker-Main-14/INFO]: [STDOUT]: {"type":"minecraft:chest","pools":[{"rolls":1.0,"bonus_rolls":0.0,"entries":[{"type":"minecraft:item","name":"minecraft:stone_axe"},{"type":"minecraft:item","weight":3,"name":"minecraft:wooden_axe"}]},{"rolls":1.0,"bonus_rolls":0.0,"entries":[{"type":"minecraft:item","name":"minecraft:stone_pickaxe"},{"type":"minecraft:item","weight":3,"name":"minecraft:wooden_pickaxe"}]},{"rolls":3.0,"bonus_rolls":0.0,"entries":[{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":1.0,"max":2.0},"add":false}],"name":"minecraft:apple"},{"type":"minecraft:item","weight":3,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":1.0,"max":2.0},"add":false}],"name":"minecraft:bread"},{"type":"minecraft:item","weight":3,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":1.0,"max":2.0},"add":false}],"name":"minecraft:salmon"}]},{"rolls":4.0,"bonus_rolls":0.0,"entries":[{"type":"minecraft:item","weight":10,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":1.0,"max":12.0},"add":false}],"name":"minecraft:stick"},{"type":"minecraft:item","weight":10,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":1.0,"max":12.0},"add":false}],"name":"minecraft:oak_planks"},{"type":"minecraft:item","weight":3,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":1.0,"max":3.0},"add":false}],"name":"minecraft:oak_log"},{"type":"minecraft:item","weight":3,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":1.0,"max":3.0},"add":false}],"name":"minecraft:spruce_log"},{"type":"minecraft:item","weight":3,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":1.0,"max":3.0},"add":false}],"name":"minecraft:birch_log"},{"type":"minecraft:item","weight":3,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":1.0,"max":3.0},"add":false}],"name":"minecraft:jungle_log"},{"type":"minecraft:item","weight":3,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":1.0,"max":3.0},"add":false}],"name":"minecraft:acacia_log"},{"type":"minecraft:item","weight":3,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":1.0,"max":3.0},"add":false}],"name":"minecraft:dark_oak_log"}]},{"rolls":1.0,"bonus_rolls":0.0,"entries":[{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:artichoke_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:asparagus_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:bellpepper_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:blackbean_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:blackberry_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:blueberry_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:broccoli_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:cabbage_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:cantaloupe_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:cauliflower_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:celery_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:coffee_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:corn_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:cranberry_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:cucumber_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:currant_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:eggplant_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:elderberry_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:garlic_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:grape_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:greenbean_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:greenonion_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:honeydew_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:hops_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:kale_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:kiwi_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:leek_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:lettuce_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:olive_seed"},{"type":"minecraft:item","weight":5,"functions":[{"function":"minecraft:set_count","count":{"type":"minecraft:uniform","min":3.0,"max":8.0},"add":false}],"name":"croptopia:onion_seed"},{"ty
[06:39:03] [Worker-Main-14/ERROR]: Parsing error loading custom advancement twigs:recipes/stripped_bamboo_planks: Unknown item tag 'twigs:stripped_bamboo_logs'
rate limit exceeded
[06:39:14] [main/ERROR]: Feature: Not a JSON object: null; Not a JSON object: "minecraft:classic_vines_cave_feature"; Not a JSON object: "minecraft:spore_blossom"; Not a JSON object: "minecraft:lush_caves_vegetation"; Not a JSON object: "minecraft:lush_caves_clay"; Not a JSON object: "minecraft:cave_vines"; Not a JSON object: "minecraft:lush_caves_ceiling_vegetation"; Not a JSON object: "minecraft:kelp_warm"; Not a JSON object: "minecraft:seagrass_simple"; Not a JSON object: "minecraft:seagrass_deep_warm"; Not a JSON object: "minecraft:spring_lava"; Not a JSON object: "minecraft:prototype_spring_water"; Not a JSON object: "minecraft:patch_pumpkin"; Not a JSON object: "minecraft:patch_sugar_cane"; Not a JSON object: "minecraft:red_mushroom_normal"; Not a JSON object: "minecraft:brown_mushroom_normal"; Not a JSON object: "minecraft:patch_grass_badlands"; Not a JSON object: "minecraft:flower_default"; Not a JSON object: "minecraft:trees_water"; Not a JSON object: "minecraft:prototype_glow_lichen"
[06:39:15] [main/INFO]: Applied 2124 biome modifications to 70 of 70 new biomes in 321.7 ms
[06:39:15] [main/WARN]: culinaire:poison_resistance missing from registry, but requested!
[06:39:15] [main/WARN]: culinaire:fulfillment missing from registry, but requested! [06:39:15] [main/WARN]: culinaire:foresight missing from registry, but requested! [06:39:15] [main/WARN]: culinaire:guard missing from registry, but requested!
[06:39:15] [main/INFO]: [fabric-registry-sync] Loaded registry data [file 1/4]
[06:39:15] [Server thread/INFO]: [megane] Loaded Config.
[06:39:15] [Server thread/INFO]: Starting minecraft server version 1.17
[06:39:15] [Server thread/INFO]: Loading properties
[06:39:15] [Server thread/INFO]: Default game type: SURVIVAL
[06:39:15] [Server thread/INFO]: Generating keypair
[06:39:15] [Server thread/INFO]: Starting Minecraft server on IP:port
rate limit exceeded
[06:39:16] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[06:39:17] [Worker-Main-13/INFO]: Preparing spawn area: 0%
[06:39:18] [Worker-Main-10/INFO]: Preparing spawn area: 0%
[06:39:18] [Worker-Main-9/INFO]: Preparing spawn area: 0%
[06:39:21] [Worker-Main-11/INFO]: Preparing spawn area: 27%
[06:39:21] [Worker-Main-13/INFO]: Preparing spawn area: 27%
[06:39:21] [Worker-Main-13/INFO]: Preparing spawn area: 27%
[06:39:21] [Worker-Main-13/INFO]: Preparing spawn area: 27%
rate limit exceeded 
[06:41:55] [User Authenticator #1/INFO]: UUID of player John is xxxx
[06:41:58] [Server thread/INFO]: John[/IP:port] logged in with entity id 66 at (125.30000001192093, 110.0, -346.69999998807907)
[06:41:58] [Server thread/INFO]: John joined the game
[06:41:58] [Server thread/INFO]: [STDOUT]: 1 air
[06:41:58] [Netty Epoll Server IO #2/ERROR]: java.lang.IllegalArgumentException: Packet too big (is 2740454, should be less than 2097152): net.minecraft.class_2788@37a688cf
[06:41:59] [Server thread/INFO]: John lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Packet too big (is 2740454, should be less than 2097152): net.minecraft.class_2788@37a688cf
[06:41:59] [Server thread/INFO]: John left the game

**Comment by finallion** [comment]
Seems to be the result of my mod adding too many recipes and minecraft cant keep up (https://bugs.mojang.com/browse/MC-185901). I'll look into reducing recipe number and / or making recipe loading more efficient.

**Comment by finallion** [comment]
I reduced the recipes from about 2500 to 2000 in the newest version. Dont know if this changes anything though... You might want to look into mods which increase the packet size. If you can provide the crash logs - that would be helpful too.

**Comment by jaded33** [comment]
[latest.log](https://github.com/finallion/Artificial_Foliage-FABRIC-/files/6744735/latest.log)

Okay tried out 1.5 tonight and same issue as 1.1-1.5 sadly

**Comment by SplendidAlakey** [comment]
Just tried out 1.5 as well and was facing the same issues with the same exact mods I had previously. Removing some recipe heavy mods certainly helped and brought the packet size down (the 1.5 update itself has brought it down by a large amount), sadly, that was not enough. There are multiple mods that fix the issue (e.g. [XL Packets](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric) and [RandomPatches](https://www.curseforge.com/minecraft/mc-mods/randompatches-fabric)), however, none of them are updated for MC 1.17.

Since the issue is not directly caused by this mod I suppose there is no point keeping it open. Thanks for the quick reply and the update, though.

**Comment by finallion** [comment]
Thanks a lot for testing this again, and I'm sorry it didn't fixed anything. Hopefully the packet mods update any time soon. I will also look into reducing some recipes again for 1.17.1. Maybe this time it'll do!

**Comment by jaded33** [comment]
I have been hoping for Random Patches to work on 1.17 soon as well. Didn’t know it was the recipe counts that contribute to this issue. Good to know.

**Comment by jaded33** [comment]
looks like XL Packets just updated on CurseForge
https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric

All fixed with XL packets I’m able to run 1.5 foliage now!

**Comment by SplendidAlakey** [comment]
Can confirm the updated XL Packets mod works and I am now able to run Artificial Foliage 1.5 with no issues. @finallion maybe you could recommend this mod on your mod page in case other people are having issues.

Note: do not use XL Packets with [Krypton](https://www.curseforge.com/minecraft/mc-mods/krypton), for some reason with both installed you will still get kicked from the server, except without any error message whatsoever. I previously installed Krypton to attempt to fix the large packet size issue, however, it did not help.

**Comment by finallion** [comment]
Glad to hear! I'll update the mod page with a link to XL Packets!
